# ZSH Configuration

PWD=$(dirname ${${(%):-%x}:A})

# user custom enviroment
source $PWD/bootstrap.zsh

# others
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export PATH=$HOME/.composer/vendor/bin:$PATH
eval "$(rbenv init -)"
eval $(thefuck --alias)
